## KNNClassifier is used to predict descrete values that is classification.

###  A) Prediction of a person of having Diabetes using the KNNClassifier
### import the necessary libraries for usage

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import f1_score, accuracy_score,confusion_matrix,mean_squared_error, classification_report
from math import sqrt


In [2]:
#reading or loading the diabetis dataset
df=pd.read_csv('diabetes.csv')
df
#clean the the data by checkin g presence of missing values and cleansing where necessary
df.describe().T
##check the the total number of missing values if present and count
df.isna().sum()
df.isnull().sum()
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

### Extraction of target variable (outcome) from the features or the indepenedent variables
### Splitting of the dataset and taking 20-30% for testing and the rest for training the model

In [3]:
#defining the x and the y values from  the dataset
x_values=df.drop('Outcome', axis=1)
#target extraction
y_target=df['Outcome']
#splitting the dataset
x_train,x_test,y_train,y_test=train_test_split(x_values,y_target,test_size=0.20)



### Scaling the data or Data transformation

In [4]:
#init the scaler
scaler=StandardScaler()
#scaling the x_train and the x_test dataset
x_train=scaler.fit_transform(x_train)

x_test=scaler.fit_transform(x_test)

### Training the Model

In [5]:
#calculate the sqrt of the total dataset and if result is even add or subtract one to get odd value
k_value=int(sqrt(len(df)))
#init the model
model=KNeighborsClassifier(n_neighbors=k_value,p=2)
#training the model by passing the x_train values
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=27)

### Predicting using the trained model

In [6]:
#predicting the model using the x_test
prediction=model.predict(x_test)
# prediction=[1 if val>0.5 else 0 for val in prediction]
prediction

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [7]:
y_test.head(n=10)

541    1
639    0
506    1
167    0
494    0
696    1
340    0
235    1
318    0
474    0
Name: Outcome, dtype: int64

In [8]:
x_test

array([[-0.40714618,  0.22882794,  0.18265772, ...,  0.02466862,
         0.2708812 , -0.57070693],
       [-0.93626443, -0.60807289,  0.27866211, ..., -1.46489627,
        -0.9560513 , -0.48570802],
       [-1.20082356,  1.78307233,  1.04669729, ...,  0.49809622,
        -0.44994164,  0.10928431],
       ...,
       [ 2.23844505,  0.25871725, -3.27350056, ...,  0.89069472,
         0.33222783,  0.87427444],
       [-0.14258706,  1.00595013,  0.18265772, ..., -0.10234854,
        -0.37632569,  0.27928211],
       [-1.20082356, -0.81729809, -0.39336866, ..., -0.40257092,
         0.21873657, -0.99570145]])

### Model Evaluation

In [9]:
#confusion matrix
cf_matrix=confusion_matrix(y_test,prediction)
cf_matrix

array([[92, 11],
       [26, 25]])

In [10]:
#F1 score
f_score=f1_score(y_test,prediction)
f_score

0.5747126436781609

In [11]:
#accuracy
accuracy=accuracy_score(y_test,prediction)
accuracy

0.7597402597402597

In [12]:
#mean squared error
mean_error=mean_squared_error(y_test,prediction)
mean_error

0.24025974025974026

## B) Using the KNNRegressor


In [13]:
### useful for contionous results such as the the stock price fluctutions 
### Is alternative for linear regression and KNNClassifier

#use pandas to load the csv file containing the dataframe
df=pd.read_csv('diabetes.csv')
#our target is years prediction thus it a dependent variable while the rest features indepenednt variables
x_features=df.drop('Outcome', axis=1)
#Year dataset
y_target=df.Outcome


### Splitting the data

In [14]:

### split the dataset and use 20-30% of the overall dataset for testing, the rest for training the model
#splitting process
x_train,x_test,y_train,y_test=train_test_split(x_features,y_target,test_size=0.20)

### Scaling the Data

In [15]:
#init of the scaler and pass the x_train and the x_test
scaler=StandardScaler()
#scaling the x_train
x_train=scaler.fit_transform(x_train)
#scaling the x_test
x_test=scaler.fit_transform(x_test)

### Training the KNNRegressor Model

In [16]:
#init the KNNRegressor model and pass the k-value which mostly is recommended to use sqrt of the dataset size
#if the value is even we add or subract to have an odd value else we use the value.
k_val=sqrt(len(df))
#val is 4 using 3 or 5 will be the best approach. depending on the mean_square_error it will ditermine the best
k_val=int(k_val)
#init the KNNRegressor model
model=KNeighborsRegressor(n_neighbors=k_val,p=2)
#actual training
model.fit(x_train,y_train)



KNeighborsRegressor(n_neighbors=27)

### Prediction of The model

In [17]:

#lets predict the value of x_test_scaled that was 30% from the overall dataset
prediction=model.predict(x_test)
# prediction=[1 if val>0.5 else 0 for val in prediction]
prediction

array([0.07407407, 0.25925926, 0.03703704, 0.37037037, 0.48148148,
       0.40740741, 0.2962963 , 0.74074074, 0.77777778, 0.74074074,
       0.        , 0.03703704, 0.11111111, 0.03703704, 0.37037037,
       0.22222222, 0.        , 0.48148148, 0.37037037, 0.62962963,
       0.88888889, 0.33333333, 0.2962963 , 0.44444444, 0.59259259,
       0.37037037, 0.40740741, 0.11111111, 0.81481481, 0.03703704,
       0.14814815, 0.7037037 , 0.14814815, 0.        , 0.22222222,
       0.        , 0.37037037, 0.25925926, 0.        , 0.33333333,
       0.33333333, 0.81481481, 0.66666667, 0.        , 0.37037037,
       0.2962963 , 0.37037037, 0.51851852, 0.07407407, 0.03703704,
       0.2962963 , 0.03703704, 0.48148148, 0.2962963 , 0.59259259,
       0.        , 0.07407407, 0.59259259, 0.07407407, 0.37037037,
       0.18518519, 0.        , 0.25925926, 0.51851852, 0.11111111,
       0.48148148, 0.14814815, 0.11111111, 0.74074074, 0.03703704,
       0.18518519, 0.25925926, 0.59259259, 0.48148148, 0.14814

In [18]:
y_test.head(n=10)

225    0
403    0
47     0
634    0
635    1
347    0
161    0
663    1
588    1
53     1
Name: Outcome, dtype: int64

In [19]:
x_test

array([[-0.92085375, -0.9168309 ,  0.47074536, ...,  0.51343307,
        -1.11061439, -0.94179488],
       [ 1.49295863, -1.35368721,  0.47074536, ...,  0.0513133 ,
        -0.5820006 ,  0.3560701 ],
       [-0.6191272 , -1.38281097,  0.05170036, ..., -0.50323042,
         0.3216632 , -0.94179488],
       ...,
       [-0.6191272 , -0.18873705,  0.31360348, ...,  0.68287698,
        -0.97181636, -1.02291144],
       [-0.01567411, -1.00420217,  1.09931286, ...,  1.26822869,
        -0.93933171, -0.6984452 ],
       [ 1.79468518,  0.42286178, -0.05306089, ..., -0.65727034,
        -0.68536084,  0.19383698]])


### Model Evaluation

In [20]:
#mean squared error
mean_error=mean_squared_error(y_test,prediction)
mean_error

0.17323143249069176